backend:
  name: github
  repo: lucianogarzo/productora-web-v2
  branch: main
  auth_type: pkce

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
